# -*- coding: utf-8 -*-
"""starter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dZfCZYaB3J4rim2kajoBRPe9mnnKNI0K
"""

from pathlib import Path
import json
import pandas as pd

DATA = Path(__file__).parent / "data"
OUTPUT = Path(__file__).parent / "output"
OUTPUT.mkdir(exist_ok=True)

pd.set_option("display.width", 120)

# เก็บ log ของทุกแถวที่ถูกตัดออก/แก้ไข เพื่อทำ Data Quality Report ที่ตรวจสอบย้อนกลับได้
dq_log = []


def log_step(stage, metric, value, note=""):
    dq_log.append({"stage": stage, "metric": metric, "value": value, "note": note})
    print(f"[{stage}] {metric} = {value}  {note}")


def section(title):
    print("\n" + "=" * 70)
    print(title)
    print("=" * 70)


# ---------------------------------------------------------------------------
# TODO 1: Extract ข้อมูลจาก CSV, Excel และ JSON  +  Profile ก่อนแก้ไข
# ---------------------------------------------------------------------------
section("5.1  EXTRACT & PROFILE (BEFORE)")

orders_jan = pd.read_csv(DATA / "orders_2026_01.csv")
orders_feb = pd.read_csv(DATA / "orders_2026_02.csv")
customers_raw = pd.read_csv(DATA / "customers_crm.csv")
products_raw = pd.read_excel(DATA / "product_master.xlsx")

with open(DATA / "payments.json", encoding="utf-8") as f:
    payments_raw_json = json.load(f)
payments_raw = pd.json_normalize(payments_raw_json)  # flatten payment.method / payment.status


def profile(df, name):
    print(f"\n--- {name} ---")
    print("shape:", df.shape)
    print("columns:", df.columns.tolist())
    print("dtypes:\n", df.dtypes)
    print("missing per col:\n", df.isna().sum())
    print("full-row duplicates:", df.duplicated().sum())
    print("sample:\n", df.head(3))
    log_step("profile_before", f"{name}_rows", len(df))
    log_step("profile_before", f"{name}_missing_total", int(df.isna().sum().sum()))
    log_step("profile_before", f"{name}_dup_rows", int(df.duplicated().sum()))


profile(orders_jan, "orders_2026_01")
profile(orders_feb, "orders_2026_02")
profile(customers_raw, "customers_crm")
profile(products_raw, "product_master")
profile(payments_raw, "payments")

# key-level duplicate checks (business key, not full-row)
log_step("profile_before", "orders_jan_dup_order_id", int(orders_jan["order_id"].duplicated().sum()))
log_step("profile_before", "orders_feb_dup_order_id", int(orders_feb["order_id"].duplicated().sum()))
log_step("profile_before", "customers_dup_customer_id", int(customers_raw["customer_id"].duplicated().sum()))
log_step("profile_before", "products_dup_product_id", int(products_raw["product_id"].duplicated().sum()))
log_step("profile_before", "payments_dup_order_id", int(payments_raw["order_id"].duplicated().sum()))

# ---------------------------------------------------------------------------
# TODO 2: Schema alignment ของไฟล์ orders สองเดือน แล้ว concat
# ---------------------------------------------------------------------------
section("5.2  COMBINE ORDERS (schema alignment)")

# ก.พ.: ordered_at -> order_date, qty -> quantity, discount_pct("5%") -> discount(0.05)
orders_feb_aligned = orders_feb.rename(columns={"ordered_at": "order_date", "qty": "quantity"}).copy()
orders_feb_aligned["discount"] = (
    orders_feb_aligned["discount_pct"].astype(str).str.rstrip("%").astype(float) / 100
)
orders_feb_aligned = orders_feb_aligned.drop(columns=["discount_pct"])

# แปลงรูปแบบวันที่ของแต่ละเดือนตามฟอร์แมตจริงของมัน ก่อน concat (ม.ค. = ISO, ก.พ. = dd/mm/yyyy)
orders_jan["order_date"] = pd.to_datetime(orders_jan["order_date"], format="%Y-%m-%d %H:%M:%S", errors="coerce")
orders_feb_aligned["order_date"] = pd.to_datetime(
    orders_feb_aligned["order_date"], format="%d/%m/%Y %H:%M", errors="coerce"
)

# จัดลำดับคอลัมน์ให้ตรงกันก่อน concat
col_order = ["order_id", "order_date", "customer_id", "product_id", "quantity", "unit_price", "discount", "channel"]
orders_jan = orders_jan[col_order]
orders_feb_aligned = orders_feb_aligned[col_order]

orders_combined = pd.concat([orders_jan, orders_feb_aligned], ignore_index=True)
log_step("combine_orders", "rows_after_concat", len(orders_combined))
print(orders_combined.dtypes)
print(orders_combined.head(3))

# ---------------------------------------------------------------------------
# TODO 3: Clean / standardize / deduplicate + Data Quality tracking
# ---------------------------------------------------------------------------
section("5.3  TRANSFORM (clean & standardize)")

orders = orders_combined.copy()
rows_before = len(orders)

# 3a. dtype ที่เหลือ: บังคับตัวเลขให้เป็น numeric (เผื่อมีค่าปนตัวอักษรหลุดมา)
for col in ["quantity", "unit_price", "discount"]:
    orders[col] = pd.to_numeric(orders[col], errors="coerce")

# 3b. drop duplicate order_id: เก็บแถวล่าสุดตามลำดับที่ปรากฏ (keep="last")
dup_order_ids = orders["order_id"].duplicated(keep=False).sum()
orders = orders.drop_duplicates(subset="order_id", keep="last")
rows_dropped_dup = rows_before - len(orders)
log_step("clean_orders", "rows_before_dedup", rows_before)
log_step("clean_orders", "duplicate_order_id_rows_removed", rows_dropped_dup,
         "เก็บแถวล่าสุดของ order_id ที่ซ้ำ (keep=last)")
log_step("clean_orders", "rows_after_dedup", len(orders))

# customers: standardize email + province, drop duplicate customer_id
customers = customers_raw.copy()
customers["email"] = customers["email"].str.lower().str.strip()

province_map = {
    "กทม.": "Bangkok",
    "กรุงเทพมหานคร": "Bangkok",
    "Bangkok": "Bangkok",
    "ชลบุรี": "Chonburi",
    "ชลบุรี ": "Chonburi",   # มีช่องว่างท้ายคำ
    "Chonburi": "Chonburi",
    "เชียงใหม่": "Chiang Mai",
    "Chiang Mai": "Chiang Mai",
    "ภูเก็ต": "Phuket",
    "Phuket": "Phuket",
    "ระยอง": "Rayong",
    "Rayong": "Rayong",
    "ขอนแก่น": "Khon Kaen",
    "ขอนเเก่น": "Khon Kaen",  # สะกดผิด (สระเอ+สระแอ ซ้อนกัน) แต่หมายถึงจังหวัดเดียวกัน
}
orig_provinces = customers["province"].copy()
customers["province"] = customers["province"].str.strip().map(province_map).fillna(customers["province"].str.strip())
unmapped_provinces = sorted(set(customers.loc[~orig_provinces.str.strip().isin(province_map.keys()), "province"].unique()))
log_step("clean_customers", "province_values_standardized", int((orig_provinces.str.strip() != customers["province"]).sum()))
if unmapped_provinces:
    log_step("clean_customers", "province_values_unmapped", len(unmapped_provinces), str(unmapped_provinces))

cust_rows_before = len(customers)
customers = customers.drop_duplicates(subset="customer_id", keep="last")
log_step("clean_customers", "duplicate_customer_id_rows_removed", cust_rows_before - len(customers))

cust_missing_email = customers["email"].isna().sum()
log_step("clean_customers", "customers_missing_email", int(cust_missing_email),
         "ยังเก็บไว้ (email ไม่ใช่ key ที่ใช้ merge)")

# products: drop duplicate product_id (ถ้ามี), standardize text
products = products_raw.copy()
products["product_name"] = products["product_name"].str.strip()
products["category"] = products["category"].str.strip()
prod_rows_before = len(products)
products = products.drop_duplicates(subset="product_id", keep="last")
log_step("clean_products", "duplicate_product_id_rows_removed", prod_rows_before - len(products))

# payments: drop duplicate order_id (เก็บ record ล่าสุดตาม paid_at ถ้ามีซ้ำ)
payments = payments_raw.copy()
payments["paid_at"] = pd.to_datetime(payments["paid_at"], errors="coerce")
pay_rows_before = len(payments)
payments = payments.sort_values("paid_at").drop_duplicates(subset="order_id", keep="last")
log_step("clean_payments", "duplicate_order_id_rows_removed", pay_rows_before - len(payments))

# ---------------------------------------------------------------------------
# TODO 4: Enrich ด้วย customer / product / payment master + validate
# ---------------------------------------------------------------------------
section("5.4  INTEGRATE & VALIDATE (merge)")

# merge กับ customer master
merged = orders.merge(
    customers[["customer_id", "province"]],
    on="customer_id", how="left", validate="many_to_one", indicator="_merge_customer"
)
unmatched_customer = (merged["_merge_customer"] == "left_only").sum()
log_step("integrate", "orders_customer_unmatched", int(unmatched_customer),
         "customer_id ไม่พบใน customers_crm")

# merge กับ product master
merged = merged.merge(
    products[["product_id", "product_name", "category", "standard_price", "active_flag"]],
    on="product_id", how="left", validate="many_to_one", indicator="_merge_product"
)
unmatched_product = (merged["_merge_product"] == "left_only").sum()
log_step("integrate", "orders_product_unmatched", int(unmatched_product),
         "product_id ไม่พบใน product_master")

# merge กับ payment (order_id ควรเป็น one-to-one)
merged = merged.merge(
    payments[["order_id", "payment.status", "payment.method", "paid_at"]],
    on="order_id", how="left", validate="one_to_one", indicator="_merge_payment"
)
unmatched_payment = (merged["_merge_payment"] == "left_only").sum()
log_step("integrate", "orders_payment_unmatched", int(unmatched_payment),
         "order_id ไม่พบข้อมูลการชำระเงิน")

print(merged[["_merge_customer", "_merge_product", "_merge_payment"]].apply(pd.Series.value_counts))

# ---------------------------------------------------------------------------
# TODO 5: Validate business rules ก่อนคำนวณยอดขาย
# ---------------------------------------------------------------------------
section("5.5  BUSINESS RULE VALIDATION")

rows_before_rules = len(merged)

reasons = pd.Series("", index=merged.index)

mask_bad_qty = ~(merged["quantity"] > 0)
mask_bad_price = ~(merged["unit_price"] > 0) | merged["unit_price"].isna()
mask_bad_discount = ~merged["discount"].between(0, 1) | merged["discount"].isna()
mask_no_customer = merged["_merge_customer"] == "left_only"
mask_no_product = merged["_merge_product"] == "left_only"
mask_not_paid = merged["payment.status"] != "PAID"

log_step("validate_rules", "excluded_quantity_not_positive", int(mask_bad_qty.sum()))
log_step("validate_rules", "excluded_unit_price_invalid", int(mask_bad_price.sum()))
log_step("validate_rules", "excluded_discount_out_of_range", int(mask_bad_discount.sum()))
log_step("validate_rules", "excluded_customer_not_in_master", int(mask_no_customer.sum()))
log_step("validate_rules", "excluded_product_not_in_master", int(mask_no_product.sum()))
log_step("validate_rules", "excluded_payment_not_paid_or_missing", int(mask_not_paid.sum()))

valid_mask = ~(mask_bad_qty | mask_bad_price | mask_bad_discount | mask_no_customer | mask_no_product | mask_not_paid)

valid_sales = merged.loc[valid_mask].copy()
log_step("validate_rules", "rows_before_rules", rows_before_rules)
log_step("validate_rules", "rows_valid_paid_sales", len(valid_sales))
log_step("validate_rules", "rows_excluded_total", rows_before_rules - len(valid_sales))

# net_sales = quantity * unit_price * (1 - discount)
valid_sales["net_sales"] = valid_sales["quantity"] * valid_sales["unit_price"] * (1 - valid_sales["discount"])
log_step("calculate", "total_net_sales", round(float(valid_sales["net_sales"].sum()), 2))

# ---------------------------------------------------------------------------
# TODO 6: Load — Dimension / Fact tables
# ---------------------------------------------------------------------------
section("5.6  LOAD (dim / fact tables)")

dim_customer = customers[["customer_id", "full_name", "email", "province", "signup_date"]].reset_index(drop=True)
dim_product = products[["product_id", "product_name", "category", "standard_price", "active_flag"]].reset_index(drop=True)

fact_sales = valid_sales[[
    "order_id", "order_date", "customer_id", "product_id",
    "quantity", "unit_price", "discount", "net_sales",
    "channel", "province", "category", "payment.status", "payment.method", "paid_at",
]].rename(columns={"payment.status": "payment_status", "payment.method": "payment_method"}).reset_index(drop=True)

dim_customer.to_csv(OUTPUT / "dim_customer.csv", index=False)
dim_product.to_csv(OUTPUT / "dim_product.csv", index=False)
fact_sales.to_csv(OUTPUT / "fact_sales.csv", index=False)

log_step("load", "dim_customer_rows", len(dim_customer))
log_step("load", "dim_product_rows", len(dim_product))
log_step("load", "fact_sales_rows", len(fact_sales))

# ---------------------------------------------------------------------------
# TODO 7: Analyze — summary by province / category
# ---------------------------------------------------------------------------
section("5.7 / 5.6  ANALYZE")

summary_by_province = (
    fact_sales.groupby("province", as_index=False)
    .agg(total_net_sales=("net_sales", "sum"), transactions=("order_id", "count"))
    .sort_values("total_net_sales", ascending=False)
)
summary_by_category = (
    fact_sales.groupby("category", as_index=False)
    .agg(total_net_sales=("net_sales", "sum"), transactions=("order_id", "count"))
    .sort_values("total_net_sales", ascending=False)
)

summary_by_province.to_csv(OUTPUT / "summary_by_province.csv", index=False)
summary_by_category.to_csv(OUTPUT / "summary_by_category.csv", index=False)

print("\nSummary by province:\n", summary_by_province)
print("\nSummary by category:\n", summary_by_category)

top_province = summary_by_province.iloc[0]
top_category = summary_by_category.iloc[0]
log_step("analyze", "top_province", top_province["province"], f"net_sales={top_province['total_net_sales']:.2f}")
log_step("analyze", "top_category", top_category["category"], f"net_sales={top_category['total_net_sales']:.2f}")

# ---------------------------------------------------------------------------
# Data Quality Report (before -> after, ตรวจสอบย้อนกลับได้ทุกขั้น)
# ---------------------------------------------------------------------------
section("DATA QUALITY REPORT")

dq_report = pd.DataFrame(dq_log)
dq_report.to_csv(OUTPUT / "data_quality_report.csv", index=False)
print(dq_report.to_string(index=False))

print(f"\n>>> ไฟล์ output ทั้งหมดถูกเขียนไปที่: {OUTPUT.resolve()}")